In [1]:
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from pandas_datareader import data

In [7]:
start, end = datetime(2018, 1, 1), datetime(2018, 2, 28)

In [10]:
hk0005 = data.DataReader('0005.HK', 'yahoo', start, end)

In [11]:
hk0004

                 High        Low       Open      Close    Volume  Adj Close
Date
2018-01-02  27.650000  27.049999  27.299999  27.600000   5569401  26.346817
2018-01-03  28.200001  27.400000  27.600000  28.150000   7607586  26.871843
2018-01-04  30.650000  28.299999  28.400000  30.600000  22355894  29.210602
2018-01-05  31.200001  29.850000  31.049999  30.799999   9911314  29.401520
2018-01-08  31.700001  30.900000  31.000000  31.250000   5808810  29.831089
2018-01-09  32.849998  31.100000  31.250000  32.599998   9671117  31.119789
2018-01-10  34.000000  32.000000  32.599998  33.349998  12183948  31.835737
2018-01-11  33.849998  32.299999  33.349998  32.700001   6487935  31.215252
2018-01-12  33.549999  32.200001  32.849998  32.349998   9315424  30.881142
2018-01-15  32.750000  32.049999  32.750000  32.150002   4832230  30.690226
2018-01-16  32.849998  32.049999  32.099998  32.549999   6259991  31.072060
2018-01-17  32.400002  31.000000  32.400002  31.750000  16427213  30.308386
2018-01-18  31.900000  30.750000  31.500000  31.000000  14293784  29.592440
2018-01-19  31.600000  30.049999  31.299999  30.500000  14122858  29.115143
2018-01-22  30.950001  30.000000  30.400000  30.700001   6776162  29.306063
2018-01-23  31.450001  30.549999  31.000000  31.250000   7914987  29.831089
2018-01-24  31.750000  31.000000  31.250000  31.549999   6853069  30.117466
2018-01-25  31.600000  31.000000  31.549999  31.600000   3612831  30.165197
2018-01-26  32.000000  31.400000  31.600000  32.000000   4398733  30.547035
2018-01-29  32.299999  31.600000  32.299999  32.000000   3800292  30.547035
2018-01-30  32.500000  31.350000  31.700001  31.700001   7461357  30.260656
2018-01-31  32.799999  31.500000  31.850000  32.049999   9966188  30.594763
2018-02-01  33.000000  32.150002  32.400002  32.299999  12707640  30.833412
2018-02-02  32.400002  31.450001  32.400002  32.099998   4806592  30.642492
2018-02-05  31.650000  30.700001  31.100000  31.299999   5305036  29.878817
2018-02-06  30.799999  29.600000  29.750000  29.900000   8832755  28.542385
2018-02-07  30.500000  28.200001  30.450001  28.450001  18861513  27.158224
2018-02-08  29.400000  28.100000  28.350000  28.250000   8958198  26.967304
2018-02-09  28.049999  26.950001  27.250000  28.000000  11349477  26.728657
2018-02-12  28.549999  27.900000  28.350000  28.049999   5026918  26.776384
2018-02-13  28.549999  28.000000  28.250000  28.200001   4914664  26.919575
2018-02-14  28.700001  27.700001  28.000000  28.650000   5531162  27.349142
2018-02-15  29.200001  28.500000  28.950001  29.049999   4816698  27.730978
2018-02-20  29.299999  28.500000  29.150000  29.049999   3983797  27.730978
2018-02-21  29.100000  28.650000  29.049999  29.000000   3845352  27.683250
2018-02-22  28.950001  28.400000  28.549999  28.500000   4672864  27.205954
2018-02-23  29.200001  28.650000  28.750000  28.900000   4698247  27.587790
2018-02-26  30.000000  28.900000  29.000000  29.799999   8897121  28.446924
2018-02-27  30.299999  29.250000  30.299999  29.500000   7792525  28.160549
2018-02-28  29.500000  28.700001  29.150000  29.299999   9056249  27.969627
2018-03-01  29.950001  28.900000  28.900000  29.900000   8804606  28.542385